# 05_01 – Типы ВС после отбора C40

Проверяем актуальную выборку эксперимента. Пересчитываем пропуски typecode, icaoaircrafttype, AC_CLASS и статусы ранее выполненного справочного сопоставления. Отдельно проверяем пять неразрешенных значений из 03: 82R, G-V, G550, GL6T, X.

Исходные значения не меняем. Смешение кода типа и составной классификации диагностируется по форме строки; несовпадение с шаблоном само по себе не доказывает ошибку. Пропуск типа не означает непригодность наблюдения для всех моделей. Справочные статусы относятся к ограниченному разбору 03, а не полной проверке всех типов.

In [1]:
# Находим проект и проверяем типы ВС в актуальной выборке
from pathlib import Path
import sys
from IPython.display import display
ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / 'europe/scripts/audit_aircraft_types.py').exists())
sys.path.insert(0, str(ROOT / 'europe/scripts'))
import audit_aircraft_types as audit
results, journal = audit.main()
display(results['quality'])
print(journal)

                                  check     rows  go_arounds  ga_percent
0                              all_rows  6331494       18358    0.289947
2             either_type_field_missing   285329         911    0.319281
5              icaoaircrafttype_missing   281738         898    0.318736
9                      typecode_missing   221671         701    0.316234
1              both_type_fields_missing   218080         688    0.315481
6    icaoaircrafttype_nonstandard_shape     4924          11    0.223396
7           reference_status_unresolved      502           2    0.398406
3                 five_unresolved_codes      502           2    0.398406
4  icaoaircrafttype_empty_or_whitespace        0           0         NaN
8          typecode_empty_or_whitespace        0           0         NaN

{'input': 'europe\\data\\analytical\\04_c40_available.parquet', 'input_sha256': 'f51a710fd9a11fe7003776748c3dc4f5792d81496713d96fb59c8c8f256e717e', 'input_unchanged': True, 'rows_checked': 6331494, 'go_arounds': 18358, 'unresolved_rows': 502, 'unresolved_go_arounds': 2, 'rows_if_five_codes_excluded': 6330992, 'go_arounds_if_five_codes_excluded': 18356, 'rows_changed': 0, 'rows_deleted': 0, 'filter_applied': False, 'classification_shape_is_diagnostic_only': True, 'reference_historical_applicability_verified': False}

In [2]:
# Показываем распределения полей и сочетаний кодов
for field in ['typecode', 'icaoaircrafttype', 'AC_CLASS', 'aircraft_reference_status', 'code_pairs']:
    print(field)
    display(results[field].head(30))
# Полные таблицы сохранены в отчетах без ограничения числа строк

typecode

    typecode     rows  go_arounds  ga_percent
21      A320  1269030        3908    0.307952
73      B738   967666        2819    0.291320
18      A319   605034        1605    0.265274
25      A321   420030        1531    0.364498
11      A20N   272273         734    0.269582
320      NaN   221671         701    0.316234
172     E190   183945         462    0.251162
173     E195   183216         436    0.237970
88      B77W   169748         637    0.375262
154     CRJ9   130515         275    0.210704
31      A333   118132         326    0.275962
90      B789   115002         332    0.288691
83      B772    92235         183    0.198406
30      A332    88900         227    0.255343
89      B788    84526         174    0.205854
72      B737    82761         158    0.190911
38      A359    79820         187    0.234277
12      A21N    74152         270    0.364117
182     E75L    72678         126    0.173367
81      B763    62581         175    0.279638
93      BCS3    59996         298    0.496700
17      A318    59484         186    0.312689
155     CRJX    58043          72    0.124046
87      B77L    57165         156    0.272894
166     DH8D    49336         128    0.259445
183     E75S    48358          93    0.192316
41      A388    46032         188    0.408412
76      B744    43990         162    0.368266
78      B752    42826         118    0.275534
171     E170    39925         114    0.285535

icaoaircrafttype

   icaoaircrafttype     rows  go_arounds  ga_percent
26              L2J  5759717       16483    0.286177
35              NaN   281738         898    0.318736
30              L4J   154695         606    0.391739
28              L2T   106784         247    0.231308
29              L3J    15521          98    0.631403
25              L1T     5775           9    0.155844
24              L1P     1784           2    0.112108
3              A332     1115           1    0.089686
1              A21N      677           7    1.033973
19             GLF6      558           0    0.000000
11             FA8X      516           1    0.193798
0               82R      450           2    0.444444
5              B734      449           0    0.000000
7              C68A      330           0    0.000000
15             GL5T      301           0    0.000000
27              L2P      196           3    1.530612
21              H1T      154           0    0.000000
32              L4T      131           1    0.763359
9              F2TH      129           0    0.000000
10             FA7X      116           0    0.000000
18             GLF5       60           0    0.000000
6              BE4W       60           0    0.000000
22              H2T       57           0    0.000000
17             GLEX       45           0    0.000000
13             G550       36           0    0.000000
14             GA6C       21           0    0.000000
4              AT76       20           0    0.000000
20              H1P       15           0    0.000000
8              E300       11           0    0.000000
34             LJ40       10           0    0.000000

AC_CLASS

  AC_CLASS     rows  go_arounds  ga_percent
5       MJ  4994980       14424    0.288770
0        H  1169132        3550    0.303644
6       MT   108711         238    0.218929
2       LJ    45304         105    0.231768
4       LT    11997          36    0.300075
7       ZZ      702           0    0.000000
3       LP      645           5    0.775194
1      HEL       23           0    0.000000

aircraft_reference_status

       aircraft_reference_status     rows  go_arounds  ga_percent
1                   not_reviewed  6044832       17449    0.288660
2     source_description_missing   281738         898    0.318736
0  direct_unique_reference_match     4422           9    0.203528
3                     unresolved      502           2    0.398406

code_pairs

    typecode icaoaircrafttype     rows  go_arounds  ga_percent
21      A320              L2J  1269030        3908    0.307952
75      B738              L2J   967666        2819    0.291320
18      A319              L2J   605034        1605    0.265274
25      A321              L2J   420030        1531    0.364498
11      A20N              L2J   272273         734    0.269582
341      NaN              NaN   218080         688    0.315481
176     E190              L2J   183945         462    0.251162
177     E195              L2J   183216         436    0.237970
92      B77W              L2J   169748         637    0.375262
158     CRJ9              L2J   130515         275    0.210704
33      A333              L2J   118132         326    0.275962
94      B789              L2J   115002         332    0.288691
85      B772              L2J    92235         183    0.198406
32      A332              L2J    88900         227    0.255343
93      B788              L2J    84526         174    0.205854
74      B737              L2J    82761         158    0.190911
40      A359              L2J    79820         187    0.234277
12      A21N              L2J    74152         270    0.364117
186     E75L              L2J    72678         126    0.173367
83      B763              L2J    62581         175    0.279638
97      BCS3              L2J    59996         298    0.496700
17      A318              L2J    59484         186    0.312689
159     CRJX              L2J    58043          72    0.124046
91      B77L              L2J    57165         156    0.272894
170     DH8D              L2T    49336         128    0.259445
187     E75S              L2J    48358          93    0.192316
43      A388              L4J    46032         188    0.408412
78      B744              L4J    43990         162    0.368266
80      B752              L2J    42826         118    0.275534
175     E170              L2J    39925         114    0.285535

In [3]:
# Сравниваем оставшиеся неразрешенные значения по адресам ВС
display(results['unresolved_aircraft'])

,icaoaircrafttype,icao24,registration,rows,go_arounds,first_landing,last_landing
0,82R,4a09ae,YRBMN,450,2,2019-01-05 17:56:33+00:00,2022-09-04 20:06:12+00:00
1,G-V,a660f6,N51VE,6,0,2019-03-19 11:02:24+00:00,2023-01-30 11:55:12+00:00
2,G550,424b5e,MHERI,16,0,2020-02-09 20:56:51+00:00,2023-04-06 10:34:33+00:00
3,G550,4d0206,LXPHS,10,0,2019-04-03 18:24:12+00:00,2022-02-15 16:20:40+00:00
4,G550,c032a0,CFTEL,10,0,2021-10-04 14:10:28+00:00,2023-01-13 19:02:17+00:00
5,GL6T,4911f5,CSDOU,10,0,2021-05-17 10:55:18+00:00,2022-06-21 17:06:54+00:00

## Ограничения и дальнейшее решение

Историческая применимость справочника и тип конкретного борта во все даты наблюдений не подтверждены. На этом шаге только оцениваем объем и последствия возможного исключения пяти неразрешенных кодов. Более широкие ограничения по типам и классам ВС требуют самостоятельного обоснования.

Предыдущий разбор и официальные источники: [03 – неразрешенные типы](../../reports/preparation/05_unresolved_aircraft_review.md), [03 – справочное сопоставление](../../reports/preparation/03_aircraft_code_review.md). Новые сетевые проверки на данном шаге не выполнялись.

Осталось 502 строки с четырьмя неразрешенными значениями и две положительные метки. X отсутствует после отбора C40. [Итоги и последствия возможного исключения](../../reports/aircraft_types/05_01_review.md).