> Итог этапа 06: решения приняты. Актуальная выборка `06_05_cases_excluded.parquet` содержит 6 331 485 строк и 18 349 GoA=True. Расчеты ниже сохраняют исторический вход этого шага. Общий итог: `europe/reports/attempts/README.md`.

# 06_04 – Записи с 4–9 попытками

Диагностика семи строк актуальной выборки; число попыток не является правилом удаления.

In [1]:
from pathlib import Path
import sys
from IPython.display import display, Markdown
ROOT = next(path for path in [Path.cwd(), *Path.cwd().parents] if (path / "europe/scripts/audit_high_attempt_cases.py").exists())
sys.path.insert(0, str(ROOT / "europe/scripts"))
from audit_high_attempt_cases import main
summary, intervals, journal = main()

## Семь случаев

Окно между первой и последней отметками, последовательности ВПП и разрыв до landing_time.

In [2]:
display(summary)
display(intervals)

,flight_id,icao24,callsign,registration,typecode,airport,landing_time,n_attempts,GoA,market_segment,runway_sequence,first_attempt,last_attempt,attempt_window_minutes,min_gap_minutes,max_gap_minutes,last_attempt_to_landing_seconds,author_callsign_prefix_filter_match,mission_verified
0,KLM1386_51283,484f16,KLM1386,PHBGW,B737,EHAM,2020-02-09 15:43:28+00:00,4,True,Mainline,18C|18C|22|18C,2020-02-09 15:07:32+00:00,2020-02-09 15:43:28+00:00,35.933333,10.866667,12.966667,0.0,False,False
1,AOJ92R_7113,4401a3,AOJ92R,OELDR,GLEX,EDDB,2020-04-22 13:56:21+00:00,4,True,Business,07L|07L|07L|07L,2020-04-22 13:18:06+00:00,2020-04-22 13:56:04+00:00,37.966667,8.750000,14.950000,17.0,False,False
2,ENF04_4658,30056b,ENF04,IENAV,P180,LIMC,2021-02-26 11:38:19+00:00,5,True,NaN,35L|35L|35L|35L|35L,2021-02-26 10:55:57+00:00,2021-02-26 11:37:51+00:00,41.900000,9.133333,11.216667,28.0,True,False
3,FHXRG_5452,39de26,FHXRG,FHXRG,GLEX,LSGG,2021-03-20 20:24:23+00:00,4,True,Business,04|22|04|04,2021-03-20 19:37:52+00:00,2021-03-20 20:24:16+00:00,46.400000,6.066667,21.000000,7.0,False,False
4,ECKJQ_17683,34304f,ECKJQ,ECKJQ,B350,LEMD,2021-07-02 16:09:52+00:00,4,True,Business,18R|18L|18L|18R,2021-07-02 14:35:05+00:00,2021-07-02 16:09:25+00:00,94.333333,19.716667,37.633333,27.0,True,False
5,KLM28Q_91412,484ee4,KLM28Q,PHHSD,B738,EHAM,2022-01-31 08:57:25+00:00,4,True,Mainline,27|27|27|27,2022-01-31 08:26:38+00:00,2022-01-31 08:57:25+00:00,30.783333,9.450000,10.916667,0.0,False,False
6,CFL12_27984,4ab179,CFL12,SELKY,BE20,ESSA,2022-11-12 10:07:17+00:00,9,True,Business,26|26|26|26|26|08|08|19L|19L,2022-11-12 07:47:14+00:00,2022-11-12 09:37:43+00:00,110.483333,6.866667,32.083333,1774.0,True,False

,flight_id,icao24,airport,landing_time,attempt_from,attempt_to,from_runway,to_runway,time_from,time_to,gap_seconds
0,KLM1386_51283,484f16,EHAM,2020-02-09 15:43:28+00:00,1,2,18C,18C,2020-02-09 15:07:32+00:00,2020-02-09 15:20:30+00:00,778.0
1,KLM1386_51283,484f16,EHAM,2020-02-09 15:43:28+00:00,2,3,18C,22,2020-02-09 15:20:30+00:00,2020-02-09 15:31:22+00:00,652.0
2,KLM1386_51283,484f16,EHAM,2020-02-09 15:43:28+00:00,3,4,22,18C,2020-02-09 15:31:22+00:00,2020-02-09 15:43:28+00:00,726.0
3,AOJ92R_7113,4401a3,EDDB,2020-04-22 13:56:21+00:00,1,2,07L,07L,2020-04-22 13:18:06+00:00,2020-04-22 13:33:03+00:00,897.0
4,AOJ92R_7113,4401a3,EDDB,2020-04-22 13:56:21+00:00,2,3,07L,07L,2020-04-22 13:33:03+00:00,2020-04-22 13:47:19+00:00,856.0
5,AOJ92R_7113,4401a3,EDDB,2020-04-22 13:56:21+00:00,3,4,07L,07L,2020-04-22 13:47:19+00:00,2020-04-22 13:56:04+00:00,525.0
6,ENF04_4658,30056b,LIMC,2021-02-26 11:38:19+00:00,1,2,35L,35L,2021-02-26 10:55:57+00:00,2021-02-26 11:06:28+00:00,631.0
7,ENF04_4658,30056b,LIMC,2021-02-26 11:38:19+00:00,2,3,35L,35L,2021-02-26 11:06:28+00:00,2021-02-26 11:17:30+00:00,662.0
8,ENF04_4658,30056b,LIMC,2021-02-26 11:38:19+00:00,3,4,35L,35L,2021-02-26 11:17:30+00:00,2021-02-26 11:28:43+00:00,673.0
9,ENF04_4658,30056b,LIMC,2021-02-26 11:38:19+00:00,4,5,35L,35L,2021-02-26 11:28:43+00:00,2021-02-26 11:37:51+00:00,548.0
10,FHXRG_5452,39de26,LSGG,2021-03-20 20:24:23+00:00,1,2,04,22,2021-03-20 19:37:52+00:00,2021-03-20 19:58:52+00:00,1260.0
11,FHXRG_5452,39de26,LSGG,2021-03-20 20:24:23+00:00,2,3,22,04,2021-03-20 19:58:52+00:00,2021-03-20 20:04:56+00:00,364.0
12,FHXRG_5452,39de26,LSGG,2021-03-20 20:24:23+00:00,3,4,04,04,2021-03-20 20:04:56+00:00,2021-03-20 20:24:16+00:00,1160.0
13,ECKJQ_17683,34304f,LEMD,2021-07-02 16:09:52+00:00,1,2,18R,18L,2021-07-02 14:35:05+00:00,2021-07-02 15:12:43+00:00,2258.0
14,ECKJQ_17683,34304f,LEMD,2021-07-02 16:09:52+00:00,2,3,18L,18L,2021-07-02 15:12:43+00:00,2021-07-02 15:49:42+00:00,2219.0
15,ECKJQ_17683,34304f,LEMD,2021-07-02 16:09:52+00:00,3,4,18L,18R,2021-07-02 15:49:42+00:00,2021-07-02 16:09:25+00:00,1183.0
16,KLM28Q_91412,484ee4,EHAM,2022-01-31 08:57:25+00:00,1,2,27,27,2022-01-31 08:26:38+00:00,2022-01-31 08:36:05+00:00,567.0
17,KLM28Q_91412,484ee4,EHAM,2022-01-31 08:57:25+00:00,2,3,27,27,2022-01-31 08:36:05+00:00,2022-01-31 08:47:00+00:00,655.0
18,KLM28Q_91412,484ee4,EHAM,2022-01-31 08:57:25+00:00,3,4,27,27,2022-01-31 08:47:00+00:00,2022-01-31 08:57:25+00:00,625.0
19,CFL12_27984,4ab179,ESSA,2022-11-12 10:07:17+00:00,1,2,26,26,2022-11-12 07:47:14+00:00,2022-11-12 07:54:06+00:00,412.0
20,CFL12_27984,4ab179,ESSA,2022-11-12 10:07:17+00:00,2,3,26,26,2022-11-12 07:54:06+00:00,2022-11-12 08:03:27+00:00,561.0
21,CFL12_27984,4ab179,ESSA,2022-11-12 10:07:17+00:00,3,4,26,26,2022-11-12 08:03:27+00:00,2022-11-12 08:10:41+00:00,434.0
22,CFL12_27984,4ab179,ESSA,2022-11-12 10:07:17+00:00,4,5,26,26,2022-11-12 08:10:41+00:00,2022-11-12 08:19:40+00:00,539.0
23,CFL12_27984,4ab179,ESSA,2022-11-12 10:07:17+00:00,5,6,26,08,2022-11-12 08:19:40+00:00,2022-11-12 08:46:11+00:00,1591.0
24,CFL12_27984,4ab179,ESSA,2022-11-12 10:07:17+00:00,6,7,08,08,2022-11-12 08:46:11+00:00,2022-11-12 08:56:36+00:00,625.0
25,CFL12_27984,4ab179,ESSA,2022-11-12 10:07:17+00:00,7,8,08,19L,2022-11-12 08:56:36+00:00,2022-11-12 09:28:41+00:00,1925.0
26,CFL12_27984,4ab179,ESSA,2022-11-12 10:07:17+00:00,8,9,19L,19L,2022-11-12 09:28:41+00:00,2022-11-12 09:37:43+00:00,542.0

## Ограничения, источники и выводы

In [3]:
display(Markdown((ROOT / "europe/reports/attempts/06_04_review.md").read_text(encoding="utf8")))
journal

# 06_04 – Семь записей с 4–9 попытками

Проверка 09.10.2026 на актуальной копии после исключения TAP948_37820. Все семь строк и исходные значения сохранены. Времена ниже относятся к UTC; окно попыток не является полной длительностью полета.

| flight_id | Аэропорт | Тип | Попытки | ВПП | Окно, мин | Последняя отметка до посадки, с |
| --- | --- | --- | ---: | --- | ---: | ---: |
| KLM1386_51283 | EHAM | B737 | 4 | 18C → 18C → 22 → 18C | 35.93 | 0 |
| AOJ92R_7113 | EDDB | GLEX | 4 | 07L → 07L → 07L → 07L | 37.97 | 17 |
| ENF04_4658 | LIMC | P180 | 5 | 35L → 35L → 35L → 35L → 35L | 41.90 | 28 |
| FHXRG_5452 | LSGG | GLEX | 4 | 04 → 22 → 04 → 04 | 46.40 | 7 |
| ECKJQ_17683 | LEMD | B350 | 4 | 18R → 18L → 18L → 18R | 94.33 | 27 |
| KLM28Q_91412 | EHAM | B738 | 4 | 27 → 27 → 27 → 27 | 30.78 | 0 |
| CFL12_27984 | ESSA | BE20 | 9 | 26 → 26 → 26 → 26 → 26 → 08 → 08 → 19L → 19L | 110.48 | 1774 |

## Что показала таблица

Проверены все 6 331 493 строки текущего входа. С более чем двумя попытками осталось 148 записей, с 4–9 – семь. У всех семи GoA=True. Размеры списков согласованы, времена строго возрастают, последняя попытка не позже landing_time. Проверены 27 соседних интервалов; самый короткий – 364 секунды. Табличных признаков наложения вроде исключенного 12-секундного случая нет. Это не подтверждение каждого эксплуатационного ухода.

### Четыре записи с типами реактивных самолетов

- KLM1386_51283: четыре отметки за 35,93 минуты, переход 18C → 22 → 18C; интервалы 10,87–12,97 минуты. Возможны повторные заходы и смена ВПП, но причины и фактические маневры не установлены. Погода и диспетчерские решения не проверены.
- KLM28Q_91412: четыре отметки 27 за 30,78 минуты, интервалы 9,45–10,92 минуты; последняя совпадает с landing_time. По таблице нет оснований объявить полет учебным или ошибочным.
- AOJ92R_7113: четыре отметки 07L за 37,97 минуты, интервалы 8,75–14,95 минуты. Сегмент Business не устанавливает назначение конкретного полета.
- FHXRG_5452: четыре отметки 04 → 22 → 04 → 04, интервалы 21:00, 06:04 и 19:20. Меток 22R/04L нет; прежняя проблема обозначений LSGG напрямую здесь не повторяется. Смена противоположных направлений требует проверки траектории, но не является доказанной ошибкой. Решение сохранить LSGG не означает подтверждение этой записи.

### Три кандидата на специальное назначение

- ENF04_4658: пять отметок 35L за 41,9 минуты, typecode P180, registration IENAV. [ENAV](https://www.enav.it/en/what-we-do/we-manage-italian-airspace/flight-inspection) описывает флот P180 для летных проверок. Это контекст для гипотезы; соответствие регистрации, оператор и задача именно 26.02.2021 по первичным документам не установлены.
- ECKJQ_17683: четыре отметки 18R → 18L → 18L → 18R за 94,33 минуты; промежутки 19,72–37,63 минуты. Позывной совпадает с исключаемым префиксом ECK в коде авторов. Назначение полета 02.07.2021 не подтверждено; метка Business не снимает этот вопрос.
- CFL12_27984: девять отметок разных направлений за 110,48 минуты, registration SELKY, typecode BE20. Позывной совпадает с префиксом CFL в коде авторов. [Bromma Air Maintenance](https://bam.aero/services/) оказывает услуги летных проверок, но эта страница не связывает SELKY с оператором и исторической задачей. По использованным первичным источникам оператор этого борта не установлен.

Для CFL12 последняя отметка 12.11.2022 09:37:43 UTC, landing_time 10:07:17 UTC: разрыв **29 минут 34 секунды**. В остальных шести строках разрыв 0–28 секунд. Это отдельная особенность границы события: таблица не объясняет, почему финальная посадка настолько позднее последней попытки. Автоматически добавлять попытку, менять посадку или GoA нельзя.

## Сравнение с кодом авторов

В ячейке 5 [ноутбука авторов](https://github.com/figuetbe/OSN23-GoA/blob/f5aaaefc6ebeb2cff8048d9fa7b1f1da2d73851d/OSN_paper_code.ipynb) применен фильтр позывных FCK, GAF, PPU, CFL, ECK, CALIBRAT, PHLAB, CALIBRA, ENF. Он затрагивает ENF04, ECKJQ и CFL12 из нашей семерки. Кроме того, авторы оставляют n_attempts < 4, поэтому все семь исключались бы этим условием из их аналитической выборки. Фильтры относятся к постановке их анализа и не доказывают ошибочность строк или специальное назначение каждого совпадения. Наш набор отличается по принятой политике; фильтры авторов не применены.

## Итог и следующий вопрос

Семь строк сохраняются. Приоритет отдельного разбора – CFL12 и разрыв 29:34 до посадки; следующий вопрос – исследовательская популяция и роль предполагаемых специальных полетов ENF04/ECKJQ/CFL12. Удаление по числу попыток не применяется. По четырем реактивным записям внутренние интервалы согласованы, реальное число уходов не подтверждено. Новых корректировок или исключений нет.

Этот шаг не разбирает оставшиеся 141 запись с тремя попытками. Полные типизированные строки: `europe/data/review/06_04_high_attempt_records.parquet`; CSV и журнал: `06_04_case_summary.csv`, `06_04_case_intervals.csv`, `06_04_case_records.csv`, `06_04_audit.json`.

## Последующее решение пользователя

CFL12 исключен по решению от 09.10.2026. Остальные шесть строк сохранены; [проверка погоды и актуальные счетчики](06_04_weather_review.md). Этот семистрочный разбор сохранен как история до исключения.

{'checked_date': '2026-10-09',
 'input': 'europe\\data\\analytical\\06_02_lsgg_case_excluded.parquet',
 'input_sha256': 'db70efe02e17a54e5d5e57147c10d395059a027eb5490d387a08eb6ee8f8a71f',
 'input_unchanged': True,
 'rows_checked': 6331493,
 'go_arounds': 18357,
 'more_than_two_attempt_rows': 148,
 'selected_rows': 7,
 'selected_go_arounds': 7,
 'attempt_count_distribution': {'4': 5, '5': 1, '9': 1},
 'intervals_checked': 27,
 'min_gap_seconds': 364.0,
 'max_last_attempt_to_landing_seconds': 1774.0,
 'author_callsign_prefix_filter_matches': 3,
 'author_filter_also_requires_n_attempts_below_4': True,
 'author_filter_applied': False,
 'mission_verified': False,
 'trajectory_validation_performed': False,
 'rows_changed': 0,
 'rows_deleted': 0,
 'extract': 'europe\\data\\review\\06_04_high_attempt_records.parquet',
 'extract_sha256': 'da66e8e638d71401d6cb267aad6cc8e86eab4fb892c27d33d0e840d404f50bfb',
 'structural_checks_passed': True}

## Решение по CFL12 и исторические METAR – 09.10.2026

Первоначальный разбор семи строк выше сохранен как история. CFL12 исключен; остальные шесть сохраняются. Далее – погодная проверка.

In [4]:
import pandas as pd
display(pd.read_csv(ROOT / "europe/reports/attempts/06_04_weather_summary.csv"))
display(pd.read_csv(ROOT / "europe/reports/attempts/06_04_weather_at_attempts.csv"))
display(Markdown((ROOT / "europe/reports/attempts/06_04_weather_review.md").read_text(encoding="utf8")))

,flight_id,airport,date_utc,daily_reports,daily_max_wind_speed_kt,daily_max_reported_gust_kt,event_metars,event_wind_speed_min_kt,event_wind_speed_max_kt,event_max_reported_gust_kt,event_max_metar_age_minutes,all_event_reports_CAVOK
0,KLM1386_51283,EHAM,2020-02-09,48,41,60.0,2,36,41,60.0,25.500000,False
1,AOJ92R_7113,EDDB,2020-04-22,48,14,22.0,3,10,12,NaN,28.100000,True
2,ENF04_4658,LIMC,2021-02-26,47,6,NaN,2,2,3,NaN,27.500000,True
3,FHXRG_5452,LSGG,2021-03-20,49,23,32.0,3,13,14,NaN,17.866667,True
4,ECKJQ_17683,LEMD,2021-07-02,48,15,20.0,4,12,15,NaN,19.700000,True
5,KLM28Q_91412,EHAM,2022-01-31,48,34,49.0,2,34,34,46.0,22.000000,False

,flight_id,airport,event,event_utc,metar_utc,age_minutes,metar
0,KLM1386_51283,EHAM,attempt_1,2020-02-09 15:07:32+00:00,2020-02-09 14:55:00+00:00,12.533333,EHAM 091455Z 20036G48KT 170V230 9999 BKN019 11...
1,KLM1386_51283,EHAM,attempt_2,2020-02-09 15:20:30+00:00,2020-02-09 14:55:00+00:00,25.500000,EHAM 091455Z 20036G48KT 170V230 9999 BKN019 11...
2,KLM1386_51283,EHAM,attempt_3,2020-02-09 15:31:22+00:00,2020-02-09 15:25:00+00:00,6.366667,EHAM 091525Z 20041G60KT 170V230 8000 -DZ BKN01...
3,KLM1386_51283,EHAM,attempt_4,2020-02-09 15:43:28+00:00,2020-02-09 15:25:00+00:00,18.466667,EHAM 091525Z 20041G60KT 170V230 8000 -DZ BKN01...
4,KLM1386_51283,EHAM,landing,2020-02-09 15:43:28+00:00,2020-02-09 15:25:00+00:00,18.466667,EHAM 091525Z 20041G60KT 170V230 8000 -DZ BKN01...
5,AOJ92R_7113,EDDB,attempt_1,2020-04-22 13:18:06+00:00,2020-04-22 12:50:00+00:00,28.100000,EDDB 221250Z 10011KT 060V130 CAVOK 18/02 Q1025...
6,AOJ92R_7113,EDDB,attempt_2,2020-04-22 13:33:03+00:00,2020-04-22 13:20:00+00:00,13.050000,EDDB 221320Z 09010KT 040V120 CAVOK 18/01 Q1025...
7,AOJ92R_7113,EDDB,attempt_3,2020-04-22 13:47:19+00:00,2020-04-22 13:20:00+00:00,27.316667,EDDB 221320Z 09010KT 040V120 CAVOK 18/01 Q1025...
8,AOJ92R_7113,EDDB,attempt_4,2020-04-22 13:56:04+00:00,2020-04-22 13:50:00+00:00,6.066667,EDDB 221350Z 06012KT 040V110 CAVOK 18/03 Q1024...
9,AOJ92R_7113,EDDB,landing,2020-04-22 13:56:21+00:00,2020-04-22 13:50:00+00:00,6.350000,EDDB 221350Z 06012KT 040V110 CAVOK 18/03 Q1024...
10,ENF04_4658,LIMC,attempt_1,2021-02-26 10:55:57+00:00,2021-02-26 10:50:00+00:00,5.950000,LIMC 261050Z VRB02KT CAVOK 18/02 Q1028 NOSIG
11,ENF04_4658,LIMC,attempt_2,2021-02-26 11:06:28+00:00,2021-02-26 10:50:00+00:00,16.466667,LIMC 261050Z VRB02KT CAVOK 18/02 Q1028 NOSIG
12,ENF04_4658,LIMC,attempt_3,2021-02-26 11:17:30+00:00,2021-02-26 10:50:00+00:00,27.500000,LIMC 261050Z VRB02KT CAVOK 18/02 Q1028 NOSIG
13,ENF04_4658,LIMC,attempt_4,2021-02-26 11:28:43+00:00,2021-02-26 11:20:00+00:00,8.716667,LIMC 261120Z VRB03KT CAVOK 18/02 Q1028 NOSIG
14,ENF04_4658,LIMC,attempt_5,2021-02-26 11:37:51+00:00,2021-02-26 11:20:00+00:00,17.850000,LIMC 261120Z VRB03KT CAVOK 18/02 Q1028 NOSIG
15,ENF04_4658,LIMC,landing,2021-02-26 11:38:19+00:00,2021-02-26 11:20:00+00:00,18.316667,LIMC 261120Z VRB03KT CAVOK 18/02 Q1028 NOSIG
16,FHXRG_5452,LSGG,attempt_1,2021-03-20 19:37:52+00:00,2021-03-20 19:20:00+00:00,17.866667,LSGG 201920Z 02013KT CAVOK 03/M07 Q1022 NOSIG
17,FHXRG_5452,LSGG,attempt_2,2021-03-20 19:58:52+00:00,2021-03-20 19:50:00+00:00,8.866667,LSGG 201950Z 03013KT CAVOK 03/M07 Q1022 NOSIG
18,FHXRG_5452,LSGG,attempt_3,2021-03-20 20:04:56+00:00,2021-03-20 19:50:00+00:00,14.933333,LSGG 201950Z 03013KT CAVOK 03/M07 Q1022 NOSIG
19,FHXRG_5452,LSGG,attempt_4,2021-03-20 20:24:16+00:00,2021-03-20 20:20:00+00:00,4.266667,LSGG 202020Z 03014KT CAVOK 02/M08 Q1022 NOSIG
20,FHXRG_5452,LSGG,landing,2021-03-20 20:24:23+00:00,2021-03-20 20:20:00+00:00,4.383333,LSGG 202020Z 03014KT CAVOK 02/M08 Q1022 NOSIG
21,ECKJQ_17683,LEMD,attempt_1,2021-07-02 14:35:05+00:00,2021-07-02 14:30:00+00:00,5.083333,LEMD 021430Z 24013KT CAVOK 35/02 Q1017 NOSIG
22,ECKJQ_17683,LEMD,attempt_2,2021-07-02 15:12:43+00:00,2021-07-02 15:00:00+00:00,12.716667,LEMD 021500Z 24015KT CAVOK 34/01 Q1017 NOSIG
23,ECKJQ_17683,LEMD,attempt_3,2021-07-02 15:49:42+00:00,2021-07-02 15:30:00+00:00,19.700000,LEMD 021530Z 23013KT 190V250 CAVOK 35/M01 Q101...
24,ECKJQ_17683,LEMD,attempt_4,2021-07-02 16:09:25+00:00,2021-07-02 16:00:00+00:00,9.416667,LEMD 021600Z 21012KT 170V240 CAVOK 35/00 Q1016...
25,ECKJQ_17683,LEMD,landing,2021-07-02 16:09:52+00:00,2021-07-02 16:00:00+00:00,9.866667,LEMD 021600Z 21012KT 170V240 CAVOK 35/00 Q1016...
26,KLM28Q_91412,EHAM,attempt_1,2022-01-31 08:26:38+00:00,2022-01-31 08:25:00+00:00,1.633333,EHAM 310825Z 31034G44KT 280V340 8000 RA FEW018...
27,KLM28Q_91412,EHAM,attempt_2,2022-01-31 08:36:05+00:00,2022-01-31 08:25:00+00:00,11.083333,EHAM 310825Z 31034G44KT 280V340 8000 RA FEW018...
28,KLM28Q_91412,EHAM,attempt_3,2022-01-31 08:47:00+00:00,2022-01-31 08:25:00+00:00,22.000000,EHAM 310825Z 31034G44KT 280V340 8000 RA FEW018...
29,KLM28Q_91412,EHAM,attempt_4,2022-01-31 08:57:25+00:00,2022-01-31 08:55:00+00:00,2.416667,EHAM 310855Z 31034G46KT 270V340 8000 RA FEW018...
30,KLM28Q_91412,EHAM,landing,2022-01-31 08:57:25+00:00,2022-01-31 08:55:00+00:00,2.416667,EHAM 310855Z 31034G46KT 270V340 8000 RA FEW018...

# 06_04 – Исключение CFL12 и погода остальных шести случаев

Проверка 09.10.2026. CFL12_27984, ICAO24 4ab179, ESSA, landing_time 12.11.2022 10:07:17 UTC исключен по прямому решению пользователя как нетипичный для исследовательской популяции. Историческая задача полета независимо не установлена. Полная строка сохранена отдельно; GoA не переписывается.

Актуальная копия – `europe/data/analytical/06_04_cfl12_excluded.parquet`: 6 331 492 строки, 18 356 GoA=True. Проверены схема, порядок и все значения оставшихся строк, а также неизменность входа по SHA256. Теперь больше двух попыток у 147 записей: 141 с тремя, пять с четырьмя, одна с пятью. Журнал – `06_04_cfl12_exclusion_applied.json`.

## Источник и привязка времени

Из [Iowa Environmental Mesonet](https://mesonet.agron.iastate.edu/request/download.phtml) получены архивные METAR за полные UTC-дни каждого из шести случаев. Это вторичный архив переданных сообщений, а не прямое получение архивной справки национальной метеослужбы. Сам IEM указывает на ограниченный контроль качества. Исходные ответы сохранены целиком, URL и SHA256 – в `06_04_weather_manifest.json`.

Для каждой попытки и landing_time выбран последний METAR не позже события. Между сообщениями погода не интерполируется. Максимальный возраст выбранного сообщения – 28,1 минуты; фактическое состояние в конкретную секунду остается неизвестным. Станция и день/время проверены по тексту каждого METAR. EDDB использован как код станции из исторического сообщения 2020 года; современное название аэропорта не подменяет исторический идентификатор.

Отдельно сохранено окно от часа до первой попытки до часа после landing_time. Позднейшее сообщение не приписывается более раннему событию. Полные UTC-дни нужны для контекста; суточный максимум не считается ветром при попытке. Прогнозные группы TEMPO/BECMG отделяются от наблюдаемой части сообщения.

## Условия непосредственно у попыток

| Случай и дата UTC | Ветер в предшествующих METAR | Видимость и облака / CAVOK | Вывод |
| --- | --- | --- | --- |
| KLM1386, EHAM, 09.02.2020 | 200°, 36–41 kt, порывы 48–60 kt | 9999, затем 8000 м; BKN019; морось в 15:25 | Сильный порывистый ветер – существенный погодный контекст; причина каждого ухода не доказана |
| KLM28Q, EHAM, 31.01.2022 | 310°, 34 kt, порывы 44–46 kt | 8000 м, дождь; BKN032/BKN031 | Аналогично: порывистый ветер подтвержден сообщениями |
| AOJ92R, EDDB, 22.04.2020 | 060–100°, 10–12 kt | CAVOK | В использованных METAR нет сильного ветра или сообщения об ухудшении видимости; четыре отметки не объяснены |
| ENF04, LIMC, 26.02.2021 | VRB, 2–3 kt | CAVOK | Погодная гипотеза по METAR не поддерживается; специальное назначение остается гипотезой |
| FHXRG, LSGG, 20.03.2021 | 020–030°, 13–14 kt | CAVOK | METAR не показывает разворота ветра, объясняющего последовательность 04 → 22 → 04 → 04 |
| ECKJQ, LEMD, 02.07.2021 | 210–240°, 12–15 kt; температура 34–35°C | CAVOK | Высокая температура отражена; признаки сильного ветра/осадков в использованных сообщениях не найдены. Причина четырех отметок неизвестна |

kt – узлы. BKN019/031/032 – исходные коды слоя с высотой 1 900/3 100/3 200 ft; эти значения не сравниваются с минимумами конкретного захода. 9999 сохранено как код сообщения, а не точное измерение 9 999 метров. CAVOK не доказывает отсутствие всех локальных опасных явлений, сдвига ветра или турбулентности. Ограничения самолета, фактическая ВПП и минимумы не проверялись; превышение эксплуатационного ограничения не заявляется.

### Два важных ограничения по времени

- EHAM 09.02.2020 15:25: `20041G60KT`, видимость 8000, `-DZ BKN019`; `TEMPO 4000` относится к тренду, а не доказывает наблюдаемую видимость 4000 при посадке.
- LSGG порыв `G24KT` есть в сообщении 21:20 UTC, через 55 минут 37 секунд после landing_time 20:24:23. В METAR, выбранных для попыток, порывы не сообщены. Поздний порыв не используется для объяснения ранних попыток.

## Решение по оставшимся строкам

Остальные шесть строк сохраняются. Для двух KLM получен погодный контекст, совместимый с возможными повторными заходами, но GoA и количество попыток не считаются независимо подтвержденными. Для AOJ92R/FHXRG погода по сообщениям не объяснила последовательности. Для ENF04/ECKJQ проверка погоды не установила причину и не заменила проверку назначения полета. Других исключений пользователь не запрашивал.

Погода используется для аудита после события, не присоединена как признак модели. Для раннего прогноза потребуются отдельные правила времени выпуска/доступности METAR; observation timestamp сам по себе не доказывает доступность сообщения в ту же секунду.

## Артефакты

`06_04_weather_summary.csv` – сутки и условия по выбранным сообщениям; `06_04_weather_at_attempts.csv` – привязка каждой попытки и посадки к METAR; `06_04_weather_windows.csv` – расширенные окна; `06_04_weather_manifest.json` – происхождение и контрольные суммы. Все исходные поля и единицы описаны в `06_04_weather_dictionary.md`. Исторический семистрочный отчет и диагностическая копия сохранены как состояние до исключения CFL12.

## Поиск сообщений о событиях – 09.10.2026


Проверка 09.10.2026. Основная выборка и метки не изменены. Поиск публичных сообщений по регистрации, позывному, аэропорту и дате выполнен для четырех случаев; отсутствие совпадения означает результат поиска, а не отсутствие события. Полные реестры расследований и непубличные журналы операторов не проверялись.

| Случай | Дата UTC | Что установлено | Что не установлено |
| --- | --- | --- | --- |
| AOJ92R_7113, OE-LDR, EDDB | 22.04.2020 | Сообщение об инциденте, совпадающее с этой датой и бортом, не найдено | Причина четырех отметок; неисправность, тренировка и указание диспетчера не подтверждены |
| FHXRG_5452, F-HXRG, LSGG | 20.03.2021 | Сообщение об инциденте, совпадающее с этой датой и бортом, не найдено | Причина четырех отметок и смены направлений; неисправность не подтверждена |
| ENF04_4658, I-ENAV, LIMC | 26.02.2021 | Материал о передаче I-ENAV в парк летных проверок размещен на сайте ENAV | Конкретная задача полета в указанную дату и причина каждой отметки |
| ECKJQ_17683, EC-KJQ, LEMD | 02.07.2021 | Документ SENASA прямо связывает EC-KJQ с калибровкой и валидацией радионавигационных средств | Конкретная задача полета в указанную дату и причина каждой отметки |

## Подтверждение роли I-ENAV

[Материал на сайте ENAV](https://cdn-web.enav.it/content/2021-06/ENAV%20completa%20la%20flotta%20di%20P%20180.File%28ac9b9352-33e0-42d2-89f2-dd80064f8f38%29.JP4.pdf), журнал JP4 за январь 2014, PDF страницы 2–3, печатные 50–51, связывает регистрацию I-ENAV с четвертым Piaggio P180 Avanti II Flight Inspections и описывает оснащение для радиометрических и калибровочных задач. Это публикация, размещенная оператором, не отчет о нашем событии. Дата каталога 2021-06 не является датой статьи. Материал подтверждает назначение самолета в историческом контексте; не подтверждает непрерывную принадлежность и миссию 26.02.2021.

## Подтверждение роли EC-KJQ

[Документ SENASA на государственном портале закупок](https://contrataciondelestado.es/wps/wcm/connect/PLACE_es/Site/area/docAccCmpnt?DocumentIdParam=b0260171-00d6-4d9f-87eb-f28d55014765&cmpntname=GetDocumentsById&source=library&srv=cmpnt), PDF страница 41, печатная 41, приложение к контракту DSO/412/23: SENASA описывает эксплуатацию BEECH B300 EC-KJQ для калибровки и валидации радионавигационных средств. Документ ссылается на поручение ENAIRE DNA 65/2022. Это сведения позже нашего события 02.07.2021; ими нельзя доказать историческую миссию конкретного полета. Регистрация, тип и специальная роль совпадают с гипотезой, поэтому она стала лучше обоснована, чем предположение только по позывному.

## Отброшенные совпадения и границы поиска

Поиск по AOJ92R дал упоминание в другом месяце 2020 года, не 22 апреля: оно не использовано как объяснение. По OE-LDR встречаются документы о другой исторической модели самолета; регистрация без даты и типа не связывает такие материалы с нашей записью. Текущие трекеры и страницы фотографий не использованы как доказательство неисправности или исторической задачи.

Выполнен общий веб-поиск и поиск по индексированным страницам BFU Германии и SUST Швейцарии. Это не полный аудит внутренних баз этих органов; отсутствие индексированного результата не доказывает отсутствие расследования. Запросы в JSON сохранены для повторения. Сообщения операторам или ведомствам не отправлялись.

## Вывод

Для AOJ92R/FHXRG причина остается неизвестной. Для ENF04/ECKJQ роль борта в летных проверках поддержана регистрационно-специфическими материалами; задача конкретного события не подтверждена. Техническую неисправность ни для одного из четырех случаев не установили. Все четыре строки пока сохранены. Массовый фильтр позывных авторов не применен.

## Итоговое исключение четырех профилей – 09.10.2026

По прямому решению пользователя из эксперимента исключены AOJ92R_7113 (4401a3, EDDB, 22.04.2020 13:56:21 UTC), FHXRG_5452 (39de26, LSGG, 20.03.2021 20:24:23 UTC), ENF04_4658 (30056b, LIMC, 26.02.2021 11:38:19 UTC) и ECKJQ_17683 (34304f, LEMD, 02.07.2021 16:09:52 UTC). Основание – принятое пользователем ограничение исследовательской популяции: нестандартный профиль захода. Неисправность, ошибка GoA или историческая миссия не объявляются доказанными.

Актуальная выборка: `europe/data/analytical/06_04_profiles_excluded.parquet` – 6 331 488 строк, 18 352 GoA=True. Полные четыре строки сохранены в `europe/data/review/06_04_excluded_profile_records.parquet`. Схема, порядок и все значения остальных записей проверены после записи; вход сохранен без изменений по SHA256. Журнал: `europe/reports/attempts/06_04_profile_exclusion_applied.json`. Воспроизведение: `.\.venv\Scripts\python.exe europe/scripts/exclude_nonstandard_profiles.py` из корня.

Из семи первоначально разобранных случаев сохранены KLM1386_51283 и KLM28Q_91412, по четыре попытки. CFL12 исключен предыдущим отдельным решением. Теперь больше двух попыток у 143 записей: 141 с тремя и две с четырьмя. В LSGG осталось 205 372 строки, 528 GoA=True; решение сохранить аэропорт с оговоркой остается в силе. Предыдущие отчеты и их счетчики описывают исторические входные версии, а не новый состав выборки.